version: '3.5'
services:

  mkdocs:
    image: "${MKDOCS_IMAGE}"
    build:
      context: .
      dockerfile: Dockerfile    

  mkdocs-material:
    image: "${MKDOCS_MATERIAL_IMAGE}"
    build:
      context: .
      dockerfile: Dockerfile-material