FROM alpine:3.11

RUN addgroup -g 8000 -S mkdocs && adduser -u 8000 -S mkdocs -G mkdocs && \
    apk add --no-cache python3 && \
    pip3 install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir MkDocs==1.1 pymdown-extensions==6.3

# Set locale
# https://click.palletsprojects.com/en/7.x/python3/
ENV LC_ALL=en_US.utf8 \
    LANG=en_US.utf8

USER mkdocs

EXPOSE 8000

WORKDIR /app

ENTRYPOINT [ "/usr/bin/mkdocs" ]

CMD [ "serve" ]

HEALTHCHECK CMD curl --fail http://localhost:8000/ || exit 1