FROM alpine:3.11

RUN addgroup -g 8000 -S mkdocs && adduser -u 8000 -S mkdocs -G mkdocs && \
    apk add --no-cache python3 python3-dev gcc musl-dev && \
    pip3 install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir mkdocs==1.1 pymdown-extensions==7.1 mkdocs-material==5.1.1 && \
    apk del python3-dev gcc musl-dev

# Set locale
# https://click.palletsprojects.com/en/7.x/python3/
ENV LC_ALL=en_US.utf8 \
    LANG=en_US.utf8

USER mkdocs

EXPOSE 8000

WORKDIR /app

ENTRYPOINT [ "/usr/bin/mkdocs" ]

CMD [ "serve" ]

HEALTHCHECK CMD curl --fail http://localhost:8000/ || exit 1