ARG IMAGE_NAME

FROM ${IMAGE_NAME}

RUN yum install -y --setopt=tsflags=nodocs python36 python36-pip && \
    pip3 install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir MkDocs pymdown-extensions mkdocs-material && \
    yum clean all && \
    rm -rf /var/cache/yum/*

# Set locale
# https://click.palletsprojects.com/en/7.x/python3/
ENV LC_ALL=en_US.utf8 \
    LANG=en_US.utf8

EXPOSE 8000

WORKDIR /app

ENTRYPOINT [ "/usr/local/bin/mkdocs" ]

CMD [ "serve" ]